// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/hats/hat.proto

package hats

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The hat model
type Hat struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Size                 *Size    `protobuf:"bytes,3,opt,name=Size,proto3" json:"Size,omitempty"`
	Color                string   `protobuf:"bytes,4,opt,name=Color,proto3" json:"Color,omitempty"`
	Active               bool     `protobuf:"varint,5,opt,name=Active,proto3" json:"Active,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	RemovedAt            int64    `protobuf:"varint,8,opt,name=RemovedAt,proto3" json:"RemovedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hat) Reset()         { *m = Hat{} }
func (m *Hat) String() string { return proto.CompactTextString(m) }
func (*Hat) ProtoMessage()    {}
func (*Hat) Descriptor() ([]byte, []int) {
	return fileDescriptor_hat_835270b5d70f95a0, []int{0}
}
func (m *Hat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hat.Unmarshal(m, b)
}
func (m *Hat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hat.Marshal(b, m, deterministic)
}
func (dst *Hat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hat.Merge(dst, src)
}
func (m *Hat) XXX_Size() int {
	return xxx_messageInfo_Hat.Size(m)
}
func (m *Hat) XXX_DiscardUnknown() {
	xxx_messageInfo_Hat.DiscardUnknown(m)
}

var xxx_messageInfo_Hat proto.InternalMessageInfo

func (m *Hat) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Hat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hat) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *Hat) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Hat) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Hat) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Hat) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Hat) GetRemovedAt() int64 {
	if m != nil {
		return m.RemovedAt
	}
	return 0
}

// The hat size model
type Size struct {
	Inches               int32    `protobuf:"varint,1,opt,name=Inches,proto3" json:"Inches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_hat_835270b5d70f95a0, []int{1}
}
func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (dst *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(dst, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetInches() int32 {
	if m != nil {
		return m.Inches
	}
	return 0
}

func init() {
	proto.RegisterType((*Hat)(nil), "hats.Hat")
	proto.RegisterType((*Size)(nil), "hats.Size")
}

func init() { proto.RegisterFile("rpc/hats/hat.proto", fileDescriptor_hat_835270b5d70f95a0) }

var fileDescriptor_hat_835270b5d70f95a0 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xbd, 0x6a, 0x85, 0x30,
	0x18, 0x40, 0x89, 0x46, 0xab, 0x5f, 0xa1, 0xc3, 0x47, 0x29, 0x19, 0x4a, 0x09, 0x4e, 0x99, 0x2c,
	0xb4, 0x4f, 0x20, 0x3a, 0xd4, 0xa5, 0x43, 0x4a, 0x1f, 0x20, 0xd5, 0x80, 0x42, 0x6d, 0x24, 0x06,
	0x87, 0xbe, 0xe5, 0x7d, 0xa3, 0x4b, 0x62, 0xf0, 0x2e, 0x21, 0xe7, 0x1c, 0xf2, 0x0b, 0x68, 0xd7,
	0xe1, 0x75, 0x52, 0x6e, 0xf3, 0x43, 0xbd, 0x5a, 0xe3, 0x0c, 0x52, 0xcf, 0xd5, 0x85, 0x40, 0xfa,
	0xa1, 0x1c, 0x3e, 0x40, 0xd2, 0x77, 0x8c, 0x70, 0x22, 0x4a, 0x99, 0xf4, 0x1d, 0x22, 0xd0, 0x4f,
	0xb5, 0x68, 0x96, 0x04, 0x13, 0xe6, 0xf8, 0x02, 0xf4, 0x6b, 0xfe, 0xd7, 0x2c, 0xe5, 0x44, 0xdc,
	0xbf, 0x41, 0xed, 0x37, 0xa8, 0xbd, 0x91, 0xc1, 0xe3, 0x23, 0x64, 0xad, 0xf9, 0x35, 0x96, 0xd1,
	0xb0, 0xe8, 0x00, 0x7c, 0x82, 0xbc, 0x19, 0xdc, 0xbc, 0x6b, 0x96, 0x71, 0x22, 0x0a, 0x19, 0x09,
	0x9f, 0xa1, 0x6c, 0xad, 0x56, 0x4e, 0x8f, 0x8d, 0x63, 0x39, 0x27, 0x22, 0x95, 0x37, 0xe1, 0xeb,
	0xf7, 0x3a, 0xc6, 0x7a, 0x77, 0xd4, 0x53, 0xf8, 0x2a, 0xf5, 0x62, 0xf6, 0x50, 0x8b, 0xa3, 0x9e,
	0xa2, 0x8a, 0xf7, 0xf4, 0x27, 0xf7, 0x7f, 0xc3, 0xa4, 0xb7, 0xf0, 0xae, 0x4c, 0x46, 0xfa, 0xc9,
	0xc3, 0x07, 0xbc, 0x5f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xb1, 0x7b, 0xf2, 0x16, 0x01, 0x00,
	0x00,
}
