// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/hats/service.proto

package hats

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request to create a hat
type CreateHatRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Size                 *Size    `protobuf:"bytes,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Color                string   `protobuf:"bytes,3,opt,name=Color,proto3" json:"Color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHatRequest) Reset()         { *m = CreateHatRequest{} }
func (m *CreateHatRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHatRequest) ProtoMessage()    {}
func (*CreateHatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_db14f04b265508aa, []int{0}
}
func (m *CreateHatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHatRequest.Unmarshal(m, b)
}
func (m *CreateHatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHatRequest.Marshal(b, m, deterministic)
}
func (dst *CreateHatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHatRequest.Merge(dst, src)
}
func (m *CreateHatRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHatRequest.Size(m)
}
func (m *CreateHatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHatRequest proto.InternalMessageInfo

func (m *CreateHatRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateHatRequest) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *CreateHatRequest) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

// The request to find a hat
type FindHatRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindHatRequest) Reset()         { *m = FindHatRequest{} }
func (m *FindHatRequest) String() string { return proto.CompactTextString(m) }
func (*FindHatRequest) ProtoMessage()    {}
func (*FindHatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_db14f04b265508aa, []int{1}
}
func (m *FindHatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindHatRequest.Unmarshal(m, b)
}
func (m *FindHatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindHatRequest.Marshal(b, m, deterministic)
}
func (dst *FindHatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindHatRequest.Merge(dst, src)
}
func (m *FindHatRequest) XXX_Size() int {
	return xxx_messageInfo_FindHatRequest.Size(m)
}
func (m *FindHatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindHatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindHatRequest proto.InternalMessageInfo

func (m *FindHatRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// The request to delete a hat
type DeleteHatRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHatRequest) Reset()         { *m = DeleteHatRequest{} }
func (m *DeleteHatRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteHatRequest) ProtoMessage()    {}
func (*DeleteHatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_db14f04b265508aa, []int{2}
}
func (m *DeleteHatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHatRequest.Unmarshal(m, b)
}
func (m *DeleteHatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHatRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteHatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHatRequest.Merge(dst, src)
}
func (m *DeleteHatRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHatRequest.Size(m)
}
func (m *DeleteHatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHatRequest proto.InternalMessageInfo

func (m *DeleteHatRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// The response to deleting a hat
type DeleteHatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHatResponse) Reset()         { *m = DeleteHatResponse{} }
func (m *DeleteHatResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteHatResponse) ProtoMessage()    {}
func (*DeleteHatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_db14f04b265508aa, []int{3}
}
func (m *DeleteHatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHatResponse.Unmarshal(m, b)
}
func (m *DeleteHatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHatResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteHatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHatResponse.Merge(dst, src)
}
func (m *DeleteHatResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteHatResponse.Size(m)
}
func (m *DeleteHatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHatResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateHatRequest)(nil), "hats.CreateHatRequest")
	proto.RegisterType((*FindHatRequest)(nil), "hats.FindHatRequest")
	proto.RegisterType((*DeleteHatRequest)(nil), "hats.DeleteHatRequest")
	proto.RegisterType((*DeleteHatResponse)(nil), "hats.DeleteHatResponse")
}

func init() { proto.RegisterFile("rpc/hats/service.proto", fileDescriptor_service_db14f04b265508aa) }

var fileDescriptor_service_db14f04b265508aa = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x2a, 0x48, 0xd6,
	0xcf, 0x48, 0x2c, 0x29, 0xd6, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x01, 0x89, 0x49, 0x09, 0xc1, 0x65, 0x33, 0x12, 0x4b, 0x20, 0x32, 0x4a,
	0x31, 0x5c, 0x02, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0x1e, 0x89, 0x25, 0x41, 0xa9, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x60, 0xb6, 0x90, 0x1c, 0x17, 0x4b, 0x70, 0x66, 0x55, 0xaa, 0x04, 0x93, 0x02, 0xa3,
	0x06, 0xb7, 0x11, 0x97, 0x1e, 0xc8, 0x18, 0x3d, 0x90, 0x48, 0x10, 0x58, 0x5c, 0x48, 0x84, 0x8b,
	0xd5, 0x39, 0x3f, 0x27, 0xbf, 0x48, 0x82, 0x19, 0xac, 0x09, 0xc2, 0x51, 0x52, 0xe0, 0xe2, 0x73,
	0xcb, 0xcc, 0x4b, 0x41, 0x32, 0x9b, 0x8f, 0x8b, 0xc9, 0xd3, 0x05, 0x6a, 0x32, 0x93, 0xa7, 0x8b,
	0x92, 0x12, 0x97, 0x80, 0x4b, 0x6a, 0x4e, 0x2a, 0x8a, 0xfd, 0xe8, 0x6a, 0x84, 0xb9, 0x04, 0x91,
	0xd4, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x1a, 0x2d, 0x60, 0xe4, 0x62, 0xf1, 0x48, 0x2c, 0x29,
	0x16, 0xd2, 0xe3, 0xe2, 0x84, 0xfb, 0x40, 0x48, 0x0c, 0xe2, 0x30, 0x74, 0x2f, 0x49, 0x71, 0x42,
	0xc4, 0x41, 0x4a, 0xb4, 0xb8, 0xd8, 0xa1, 0x6e, 0x12, 0x12, 0x81, 0x88, 0xa2, 0x3a, 0x11, 0x59,
	0xad, 0x0d, 0x17, 0x27, 0xdc, 0x66, 0x98, 0xd9, 0xe8, 0xce, 0x95, 0x12, 0xc7, 0x10, 0x87, 0x38,
	0x31, 0x89, 0x0d, 0x1c, 0xc4, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x6c, 0x7a, 0xa4,
	0x96, 0x01, 0x00, 0x00,
}
