// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/haberdasher/haberdasher.proto

package haberdasher

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The hat model
type Hat struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Size                 *Size    `protobuf:"bytes,3,opt,name=Size,proto3" json:"Size,omitempty"`
	Color                string   `protobuf:"bytes,4,opt,name=Color,proto3" json:"Color,omitempty"`
	Active               bool     `protobuf:"varint,5,opt,name=Active,proto3" json:"Active,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	RemovedAt            int64    `protobuf:"varint,8,opt,name=RemovedAt,proto3" json:"RemovedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hat) Reset()         { *m = Hat{} }
func (m *Hat) String() string { return proto.CompactTextString(m) }
func (*Hat) ProtoMessage()    {}
func (*Hat) Descriptor() ([]byte, []int) {
	return fileDescriptor_haberdasher_17a86536b571963d, []int{0}
}
func (m *Hat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hat.Unmarshal(m, b)
}
func (m *Hat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hat.Marshal(b, m, deterministic)
}
func (dst *Hat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hat.Merge(dst, src)
}
func (m *Hat) XXX_Size() int {
	return xxx_messageInfo_Hat.Size(m)
}
func (m *Hat) XXX_DiscardUnknown() {
	xxx_messageInfo_Hat.DiscardUnknown(m)
}

var xxx_messageInfo_Hat proto.InternalMessageInfo

func (m *Hat) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Hat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hat) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *Hat) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Hat) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Hat) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Hat) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Hat) GetRemovedAt() int64 {
	if m != nil {
		return m.RemovedAt
	}
	return 0
}

// The hat size model
type Size struct {
	Inches               int32    `protobuf:"varint,1,opt,name=Inches,proto3" json:"Inches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_haberdasher_17a86536b571963d, []int{1}
}
func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (dst *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(dst, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetInches() int32 {
	if m != nil {
		return m.Inches
	}
	return 0
}

// The request to create a hat
type CreateHatRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Size                 *Size    `protobuf:"bytes,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Color                string   `protobuf:"bytes,3,opt,name=Color,proto3" json:"Color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHatRequest) Reset()         { *m = CreateHatRequest{} }
func (m *CreateHatRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHatRequest) ProtoMessage()    {}
func (*CreateHatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_haberdasher_17a86536b571963d, []int{2}
}
func (m *CreateHatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHatRequest.Unmarshal(m, b)
}
func (m *CreateHatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHatRequest.Marshal(b, m, deterministic)
}
func (dst *CreateHatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHatRequest.Merge(dst, src)
}
func (m *CreateHatRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHatRequest.Size(m)
}
func (m *CreateHatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHatRequest proto.InternalMessageInfo

func (m *CreateHatRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateHatRequest) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *CreateHatRequest) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func init() {
	proto.RegisterType((*Hat)(nil), "haberdasher.Hat")
	proto.RegisterType((*Size)(nil), "haberdasher.Size")
	proto.RegisterType((*CreateHatRequest)(nil), "haberdasher.CreateHatRequest")
}

func init() {
	proto.RegisterFile("rpc/haberdasher/haberdasher.proto", fileDescriptor_haberdasher_17a86536b571963d)
}

var fileDescriptor_haberdasher_17a86536b571963d = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x49, 0xff, 0xb9, 0x9d, 0x82, 0xcc, 0x20, 0x12, 0x44, 0xa5, 0x16, 0x84, 0x5e, 0x4d,
	0x98, 0xb7, 0xde, 0x8c, 0xed, 0xa2, 0x45, 0xf0, 0x22, 0xe2, 0x03, 0x64, 0xed, 0x81, 0x0e, 0x9c,
	0xa9, 0x69, 0xdc, 0x85, 0x4f, 0xea, 0xe3, 0x48, 0x92, 0xda, 0xb5, 0xe2, 0xc5, 0xee, 0xce, 0xf7,
	0xfd, 0x92, 0x73, 0xce, 0x97, 0xc0, 0xad, 0x6a, 0xca, 0xfb, 0x5a, 0x6c, 0x50, 0x55, 0xa2, 0xad,
	0x51, 0x0d, 0xeb, 0x79, 0xa3, 0xa4, 0x96, 0x34, 0x1e, 0x58, 0xe9, 0x37, 0x01, 0x3f, 0x17, 0x9a,
	0x9e, 0x82, 0x57, 0xac, 0x19, 0x49, 0x48, 0x36, 0xe5, 0x5e, 0xb1, 0xa6, 0x14, 0x82, 0x67, 0xb1,
	0x43, 0xe6, 0x59, 0xc7, 0xd6, 0xf4, 0x0e, 0x82, 0x97, 0xed, 0x17, 0x32, 0x3f, 0x21, 0x59, 0xbc,
	0x38, 0x9b, 0x0f, 0x5b, 0x1b, 0xc0, 0x2d, 0xa6, 0xe7, 0x10, 0xae, 0xe4, 0x9b, 0x54, 0x2c, 0xb0,
	0x77, 0x9d, 0xa0, 0x17, 0x10, 0x2d, 0x4b, 0xbd, 0xdd, 0x23, 0x0b, 0x13, 0x92, 0x4d, 0x78, 0xa7,
	0xe8, 0x15, 0x4c, 0x57, 0x0a, 0x85, 0xc6, 0x6a, 0xa9, 0x59, 0x94, 0x90, 0xcc, 0xe7, 0x07, 0xc3,
	0xd0, 0xd7, 0xa6, 0xea, 0xe8, 0x89, 0xa3, 0xbd, 0x61, 0x28, 0xc7, 0x9d, 0xdc, 0x5b, 0x3a, 0x71,
	0xb4, 0x37, 0xd2, 0x1b, 0xb7, 0xae, 0x99, 0x5c, 0xbc, 0x97, 0x35, 0xb6, 0x36, 0x5e, 0xc8, 0x3b,
	0x95, 0x96, 0x30, 0x73, 0x83, 0x72, 0xa1, 0x39, 0x7e, 0x7c, 0x62, 0xab, 0xfb, 0xd8, 0xe4, 0x9f,
	0xd8, 0xde, 0x91, 0xb1, 0xfd, 0x41, 0xec, 0xc5, 0x13, 0xc4, 0xf9, 0xe1, 0x3c, 0x7d, 0xfc, 0x4d,
	0x6b, 0xde, 0xfc, 0x7a, 0xd4, 0xea, 0xef, 0x2e, 0x97, 0xb3, 0x11, 0xce, 0x85, 0xde, 0x44, 0xf6,
	0x03, 0x1f, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x62, 0x77, 0xa3, 0xe5, 0x01, 0x00, 0x00,
}
